### ISSUE TITLE
More docs needed

### ISSUE THREAD

**Issue by fatso83** [danmbox/briss2#1]
Due to the low activity on the Briss SF page, I thought about starting my own fork, and saw yours while researching. Now I am a bit unsure of whether to fork yours to contribute or fork off the original repo, as there is very little info on what is new and what features you have contributed to the application.

Adding a README.md with an overview of the additional features and basic usage would help people finding the project. Even better would be a wiki section.

**Comment by danmbox** [comment]
The features are summarized in the briss sourceforge patch section (http://sourceforge.net/p/briss/patches/). I tried that before forking, but the maintainer was unresponsive.

You are right; I was planning on doing a point release, adding a blog post etc.

What do you want to implement?

**Comment by fatso83** [comment]
Thanks for the reponse. Basically I would like to do these
- [Create OS X Bundle](https://sourceforge.net/p/briss/feature-requests/34/)
- [Settings files on the command line](https://sourceforge.net/p/briss/feature-requests/12/)

**Comment by danmbox** [comment]
Hi, I have added a minimal changelog and a new version number. I'm willing to merge pull requests from contributors

Regarding the settings on the command line, did you notice the crop-string feature? You can get a crop-string (describing the exact setup of the crop rectangles) from the GUI menu, or make one up yourself once you understand the syntax (described in the --help text). Then you can enter crop-strings from the command line (run the jar with --help as README-briss2.txt advises to see how) or from the GUI menu.

**Comment by fatso83** [comment]
That seems great, and more or less exactly what I intended. Are you pulling in changes from the original project as well?

**Comment by danmbox** [comment]
I don't think any changes are forthcoming from the original project, but that of course may change...

The only thing that I am missing is Undo / Redo (for the times when you mess up a long sequence of splits while setting up the crop rectangles in the GUI). I wrote the code back in February but promptly lost it to a crash.

OTOH, I will accept pull requests for whatever seems useful (and consistent with the existing code and UX).
