### ISSUE TITLE
Main improvements

### ISSUE THREAD

**Issue by fatso83** [danmbox/briss2#10]
Trying to decide whether to shove improvements into this project or the [fork by @mbaeuerle](https://github.com/mbaeuerle/Briss-2.0). While that project makes the improvement apparent, it is a bit harder to find out what is new in this one.

**Comment by fatso83** [comment]
Screw that. This is dead.

**Comment by danmbox** [comment]
Well, I am interested in the fate of Briss, so it's good to know where development continues. Sorry for not replying earlier, I'm not watching this space much at the moment.
