### ISSUE TITLE
Jpedal is not avaiable anymore

### ISSUE THREAD

**Issue by anilatxg** [danmbox/briss2#2]
Jpedal LGPL version seems to have disapeared(it's sourceforge page does not exist anymore) and briss2 suggested maven assembly:single throws:
Could not find artifact jpedal:jpedal:jar:4.92b23 in geotoolkit
It seems to be used just few times in the source, maybe it could be replaced (or embedded?)

**Comment by danmbox** [comment]
I've pushed a fix (replacing geotoolkit with clojars.org). I could probably host a jpedal copy in this project, though I have to look at the licenses.
