### ISSUE TITLE
jai_imageio no longer in clojars repo?

### ISSUE THREAD

**Issue by n9yty** [danmbox/briss2#3]
Trying to build this on Mac OS X, and I get an error because maven cant' find jai_imageio in clojars.

I see it tries the following URL and I get a 404 if I try it manually also...

http://clojars.org/repo/javax/media/jai_imageio

It seems the whole javax directory is missing from there. :(

**Comment by n9yty** [comment]
I'm sorry, but I don't know much about Java or Maven projects, but I tried to swap out/add a repo for the jai_imageio stuff with this one:

https://code.google.com/p/mbari-maven-repository/source/browse/repository/javax/media/jai_imageio/

And while it "builds", there is nothing matching  briss-*.jar in the target archives. Just the following:

CHANGELOG-orig.txt
CHANGELOG.txt
LICENSE.txt
README-orig.txt
README.html
README.org
bcmail-jdk15-1.46.jar
bcprov-jdk15-1.46.jar
bctsp-jdk15-1.46.jar
itextpdf-5.2.0.jar
jai_codec-1.1.3.jar
jai_core-1.1.3.jar
jai_imageio-1.1.jar
jpedal-lgpl-4.74b27.jar

**Comment by danmbox** [comment]
fac720738cf4210223e6f7d7c62e49b603397816 seems to fix it -- I've re-enabled the geotoolkit repository which went dead for a while
