### ISSUE TITLE
"Image to Big!"

### ISSUE THREAD

**Issue by ylluminate** [danmbox/briss2#5]
Interestingly I'm still hitting the "Image to Big!" error on certain PDFs.  Have you seen what may be causing this?

**Comment by ylluminate** [comment]
So just fiddling around here, I modified [this line](https://github.com/danmbox/briss2/blob/fac720738cf4210223e6f7d7c62e49b603397816/src/main/java/at/laborg/briss/model/ClusterImageData.java#L13) to be:
`private static final int MAX_IMAGE_RENDER_SIZE = 4000 * 4000;`

Instead of the default 2000 max and it works fine now.

Any reason it's set at 2000 and not something higher so as to not hit walls like this?

**Comment by danmbox** [comment]
I don't think there's any good reason the original code imposed this limitation.

**Comment by danmbox** [comment]
Enlarged in briss2-1.0.1-rc.1
