### ISSUE TITLE
Announcement missing

### ISSUE THREAD

**Issue by fatso83** [danmbox/briss2#9]
The [homepage](http://danmbox.github.io/briss2/) for the tool mentions an announcement, but the [link](http://www.omnigia.com/news/content/briss-pdf-cropper-and-rearranger-1n-layouts) is dead/redirects to the root.

**Comment by Yu-Ishi162** [comment]
If you google with "Briss, a PDF cropper and rearranger: 1/N-up layouts", you can hit.

**Comment by fatso83** [comment]
Sure. Basically this project seems as dead in the water as the original and further efforts are best directed to the [living version by Marian Bäuerle](https://github.com/baeuerle/Briss-2.0)
